# Generated by Django 5.1.1 on 2025-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.IntegerField(choices=[(1, 'Admin'), (2, 'Cliente'), (3, 'Trabajador')], default=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
            ],
        ),
    ]
