# Generated by Django 5.1.1 on 2025-04-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo_empleo', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Remoto', 'Remoto')], max_length=50)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('salario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
