# Generated by Django 5.1.1 on 2025-04-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0002_ofertalaboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertalaboral',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ofertalaboral',
            name='salario',
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='projobs.ofertalaboral')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='projobs.usuario')),
            ],
        ),
    ]
