# Generated by Django 5.1.1 on 2025-05-19 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0005_mensajecontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='usuario',
        ),
        migrations.CreateModel(
            name='OfertaLaboralIndependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('modo_trabajo', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20)),
                ('rango_pago', models.CharField(max_length=50)),
                ('fecha_limite', models.DateField()),
                ('categoria', models.CharField(choices=[('Electricista', 'Electricista'), ('Diseñador Gráfico', 'Diseñador Gráfico'), ('Programador', 'Programador'), ('Plomero', 'Plomero'), ('Jardinero', 'Jardinero'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion_profesion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='abierta', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projobs.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='OfertaLaboral',
        ),
        migrations.DeleteModel(
            name='Postulacion',
        ),
    ]
