# Generated by Django 5.1.1 on 2025-05-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0006_remove_postulacion_oferta_remove_postulacion_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='projobs.ofertalaboralindependiente')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='projobs.usuario')),
            ],
            options={
                'unique_together': {('trabajador', 'oferta')},
            },
        ),
    ]
