# Generated by Django 5.1.1 on 2025-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0007_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
    ]
