# Generated by Django 5.1.1 on 2025-05-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0010_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
