# Generated by Django 5.1.1 on 2025-05-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0011_mensaje_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
