# Generated by Django 5.1.1 on 2025-05-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0013_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='comentario',
        ),
    ]
