# Generated by Django 5.1.1 on 2025-06-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0014_remove_usuario_calificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projobs.postulacion')),
                ('trabajador', models.ForeignKey(limit_choices_to={'rol': 3}, on_delete=django.db.models.deletion.CASCADE, to='projobs.usuario')),
            ],
        ),
    ]
