# Generated by Django 5.1.1 on 2025-07-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0015_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
