# Generated by Django 5.1.1 on 2025-07-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0016_usuario_token_recuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
