# Generated by Django 5.1.1 on 2025-07-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projobs', '0017_postulacion_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboralindependiente',
            name='max_postulaciones',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
